spring:
  jackson:
    deserialization:
      fail-on-unknown-properties: true

  datasource:
    url: "jdbc:mysql://localhost:3306/album"
    username: root
    password: root

  jpa:
    show_sql: true
    hibernate:
      ddl-auto: update


server:
  port: 8082

redis:
  host: localhost
  port: 6379
  username: auth
  password: ########
